version: '3.8'

services:

  basic-info:
    image: basic-info-java:latest
    ports:
      - "80:8080"
      - "8080:8080"
    expose: []
    networks:
      - frontend
    volumes: []
    depends_on: []

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 64M
    env_file: []
    environment: []
    secrets: []


networks:
  frontend: